### PR TITLE
[examples] Add example for sending a custom event from child to parent

### PR DESCRIPTION
**Pull request by scritch007**
I was looking for an example of sending a custom event from a child to the parent.

I hope this example is good enough. Do not hesitate to modify or report anything that isn't well done.

### CODE REVIEW

**Comment by luna-duclos** [comment]
I've noticed you import data-container.html, but don't use it, I assume that's left over from copy-pasting another example and should be removed ?

**Comment by dmitshur** [comment]
What about [line 15 of examples/custom-event/parent-container.html](https://github.com/PalmStoneGames/polymer/pull/7/files#diff-8d58927b9ac7cb6ea460062e57d4fb53R15)?

**Comment by luna-duclos** [comment]
There's a couple of changes I want to do, but for now, this example is plenty good enough

**Comment by skritchz** [comment]
Hi, yes the data-container.html should have been included by the parent-container.html file instead of the index.html.

**Pull request merged**
